# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js Alpine image as the base
FROM node:23-alpine AS builder

# Install the dependencies
RUN --mount=type=cache,target=/root/.npm npm install --ignore-scripts

# Copy the rest of the application code
COPY . /app

# Build the application
RUN npm run build

# Use a new, clean image for the release
FROM node:23-alpine

# Set the working directory
WORKDIR /app

# Copy the built files from the builder
COPY --from=builder /app/dist /app/dist

# Expose any ports if necessary (e.g., 8080)
# EXPOSE 8080

# Run the server
ENTRYPOINT ["node", "dist/index.js"]
